version: '3'

networks:
  net_dev:
    external: true
  net_log:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.10.0/16
          gateway: 172.22.10.1

x-logging: &loki-log
  logging:
    driver: loki
    options:
      loki-url: "http://172.22.10.2:3100/loki/api/v1/push"
      loki-batch-size: "100"
      loki-retries: "5"
      loki-external-labels: "container_name={{.Name}},container_id={{.ID}}"

services:
  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    user: "0"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /root/loki/local-config.yaml:/etc/loki/local-config.yaml
      - /root/loki/data:/loki/
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      net_log:
        ipv4_address: 172.22.10.2

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "0"
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "3000:3000"
    volumes:
      - /root/grafana:/var/lib/grafana
    networks:
      net_log:
        ipv4_address: 172.22.10.3

  web:
    image: 127.0.0.1:5000/gpt-web:1.0.0
    container_name: web
    ports:
      - "8081:8080"
    volumes:
      - /root/web/conf.yaml:/app/conf/conf.yaml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=PathPrefix(`/web`)"
      - "traefik.http.routers.web.middlewares=web-sp"
      - "traefik.http.middlewares.web-sp.stripprefix.prefixes=/web"
    networks:
      - net_dev
    <<: *loki-log
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - /root/mysql/data:/var/lib/mysql
      # - /root/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - 3306:3306
    networks:
      - net_dev

  traefik:
    image: traefik:v2.11
    container_name: traefik
    command: "--api.insecure=true --providers.docker=true --entrypoints.web.address=:80 --providers.docker.exposedByDefault=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=false"
    networks:
      - net_dev

  registry:
    image: registry:latest
    container_name: registry
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /root/registry/data:/var/lib/registry
    ports:
      - 5000:5000
    networks:
      - net_dev

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin123
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - /root/minio/data:/data
    command: server /data --console-address ":9001"
    networks:
      - net_dev

  nginx:
    image: nginx:latest
    container_name: nginx
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8000:80"
    volumes:
      - /root/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /root/nginx/html:/usr/share/nginx/html
      - /root/nginx/log:/var/log/nginx
    networks:
      - net_dev

  
